# Generated by Django 4.2.5 on 2023-10-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Název formátu')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Popis')),
                ('enabled', models.BooleanField(default=False, verbose_name='Povolen')),
                ('yt_dl_opts', models.JSONField()),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], verbose_name='Typ souboru')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
                ('start_datetime', models.DateField(auto_now_add=True, verbose_name='Datum START')),
                ('finish_datetime', models.DateField(null=True, verbose_name='Datum FINISH')),
                ('playlist', models.BooleanField(default=False, verbose_name='Playlist')),
                ('state', models.CharField(choices=[('ERROR', 'CHYBA'), ('SUCCESS', 'ÚSPĚCH'), ('PROCESSING', 'ZPRACOVÁVÁNÍ'), ('IN_QUEUE', 'VE FRONTĚ')], default='IN_QUEUE', verbose_name='Stav požadavku')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Module1.downloadformat', verbose_name='Formát')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256, verbose_name='Název souboru')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Module1.downloadrequest', verbose_name='Požadavek')),
            ],
        ),
    ]
