# Generated by Django 4.2.5 on 2023-10-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='playlist',
        ),
    ]
