# Generated by Django 4.2.5 on 2023-10-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0002_remove_downloadrequest_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='finish_datetime',
            field=models.DateTimeField(null=True, verbose_name='Datum FINISH'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum START'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='state',
            field=models.CharField(choices=[('SUCCESS', 'ÚSPĚCH'), ('PROCESSING', 'ZPRACOVÁVÁNÍ'), ('IN_QUEUE', 'VE FRONTĚ'), ('DOWNLOADER ERROR', 'CHYBA STAHOVÁNÍ'), ('CRITICAL ERROR', 'KRITICKÁ CHYBA')], default='IN_QUEUE', verbose_name='Stav požadavku'),
        ),
    ]
