# Generated by Django 4.2.5 on 2023-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0004_alter_downloadformat_yt_dl_opts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadformat',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='yt_dl_opts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
