# Generated by Django 4.2.5 on 2023-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0005_alter_downloadformat_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadedfile',
            old_name='request_id',
            new_name='request',
        ),
    ]
