# Generated by Django 4.2.5 on 2023-10-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('Module1', '0006_rename_request_id_downloadedfile_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='finish_datetime',
        ),
        migrations.RemoveField(
            model_name='downloadrequest',
            name='state',
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult'),
        ),
    ]
