# Generated by Django 4.2.5 on 2023-10-28 13:32

from django.db import migrations
from django.core.management import call_command


fixture = 'default_download_formats.json'
def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='Module1')

class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0008_remove_downloadrequest_start_datetime'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]


