# Generated by Django 4.2.5 on 2023-11-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0009_load_default_download_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadformat',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], null=True, verbose_name='Typ souboru'),
        ),
    ]
