# Generated by Django 4.2.5 on 2023-12-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0011_userformatpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformatpreference',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Module1.downloadformat', verbose_name='Preferovaný formát'),
        ),
    ]
