FROM python:3.10-alpine
WORKDIR /Project1
COPY requirements.txt /Project1
RUN pip install -r requirements.txt --no-cache-dir
RUN apk upgrade -U && apk add ffmpeg && rm -rf /var/cache/*
COPY ./Project1 /Project1
CMD celery -A Project1 worker --loglevel=INFO --concurrency 1